name: Deploiement flask sur aws

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: import du pépôt
        uses: actions/checkout@v4
      - name: python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: install psycopg
        run: sudo apt install -Y python3-psycopg2
      - name: pip update
        run: pip install --upgrade pip
      - name: Installation des dépendences
        run: pip install -r requirements.txt
      - name: Deploiement
        run: flask run