name: Deploiement flask sur aws

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: import du pépôt
        uses: actions/checkout@v4
      - name: install psycopg
        run: sudo apt install -y python3-psycopg2
      - name: pip update
        run: pip3 install --upgrade pip
      - name: Installation des dépendences
        run: pip3 install -r requirements.txt
      - name: Deploiement
        run: flask run